import { useState, useEffect } from "react";
import Head from "next/head";
// import Template from "../components/Template";
import Banner, { Image } from "../components/Banner";
// 导入接口
import { getimagesList } from "./api/request";
// import Card from "../components/Card";
import { Card, Toast, Button } from "antd-mobile";
import BasicInfo, { BasicInfoProps } from "../components/Fundemantalinfo";

export default function Home() {
  let imagesList: Image[] = [
    { id: "1", url: "/images/1.jpg", alt: "banner1", name: "十大正宗本帮菜" },
    { id: "2", url: "/images/2.jpg", alt: "banner2", name: "外套风情餐厅" },
    { id: "3", url: "/images/3.jpg", alt: "banner3", name: "特色风味小吃" },
    { id: "4", url: "/images/5.jpg", alt: "banner5", name: "特色风味小吃" },
  ];
  let BasicInfoProps = { name: "123", age: 123, email: "123" };
  const onClick = () => {
    Toast.show("点击了卡片");
  };

  return (
    <div>
      <Head>
        <title>美食林</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ padding: "0.5rem", backgroundColor: "grey" }}>
        <Card style={{ width: "100%", height: "220px" }} onClick={onClick}>
          <Banner images={imagesList} />
        </Card>

       
      </div>
    </div>
  );
}
